stages:
  - build
  - test

build:
  stage: build
  image: docker.npc.ba/phosgene/astra-dev:latest
  script:
    - rm -rf build && mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4

  artifacts:
    untracked: true
    expire_in: 1 day

test:
  stage: test
  dependencies: 
    - build
  image: docker.npc.ba/phosgene/astra-dev:latest
  script:
    - cd build
    - ctest -V
